In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
A = np.array([[1, 2], [2, 3.999]])
y = np.array([4, 7.999])

In [3]:
np.matmul(LA.inv(A), y)

array([2., 1.])

In [4]:
noise = (1e-3, -1e-3)
A_noisy = A + noise
A_noisy

array([[1.001, 1.999],
       [2.001, 3.998]])

In [5]:
np.matmul(LA.inv(A_noisy), y)

array([1.        , 1.50025013])

In [9]:
np.matmul(LA.inv(A), y + noise)

array([-3.999,  4.   ])

In [6]:
LA.cond(A)

24992.00096006945

In [7]:
eigs = LA.eigvals(A)
eigs

array([-2.00032004e-04,  4.99920003e+00])

In [8]:
np.matmul(LA.inv(A), y + noise)

array([-3.999,  4.   ])